name: run-tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Check code formatting
        run: dotnet format --verify-no-changes -v diagnostic

      - name: Run tests
        run: |
          echo JWT_TOKEN=$(cd src/Onyx.ProductsApi;dotnet user-jwts create --audience "http://localhost:5271" -o token) > .env
          docker compose up --build tests
